// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PostAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountRequest) Reset()         { *m = PostAccountRequest{} }
func (m *PostAccountRequest) String() string { return proto.CompactTextString(m) }
func (*PostAccountRequest) ProtoMessage()    {}
func (*PostAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{1}
}
func (m *PostAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountRequest.Unmarshal(m, b)
}
func (m *PostAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountRequest.Marshal(b, m, deterministic)
}
func (dst *PostAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountRequest.Merge(dst, src)
}
func (m *PostAccountRequest) XXX_Size() int {
	return xxx_messageInfo_PostAccountRequest.Size(m)
}
func (m *PostAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountRequest proto.InternalMessageInfo

func (m *PostAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PostAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountResponse) Reset()         { *m = PostAccountResponse{} }
func (m *PostAccountResponse) String() string { return proto.CompactTextString(m) }
func (*PostAccountResponse) ProtoMessage()    {}
func (*PostAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{2}
}
func (m *PostAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountResponse.Unmarshal(m, b)
}
func (m *PostAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountResponse.Marshal(b, m, deterministic)
}
func (dst *PostAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountResponse.Merge(dst, src)
}
func (m *PostAccountResponse) XXX_Size() int {
	return xxx_messageInfo_PostAccountResponse.Size(m)
}
func (m *PostAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountResponse proto.InternalMessageInfo

func (m *PostAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{3}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{4}
}
func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(dst, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountsRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{5}
}
func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(dst, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

func (m *GetAccountsRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetAccountsRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetAccountsReponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsReponse) Reset()         { *m = GetAccountsReponse{} }
func (m *GetAccountsReponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsReponse) ProtoMessage()    {}
func (*GetAccountsReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_cf6ab7fb5d06f5ed, []int{6}
}
func (m *GetAccountsReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsReponse.Unmarshal(m, b)
}
func (m *GetAccountsReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsReponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountsReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsReponse.Merge(dst, src)
}
func (m *GetAccountsReponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsReponse.Size(m)
}
func (m *GetAccountsReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsReponse proto.InternalMessageInfo

func (m *GetAccountsReponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "pb.Account")
	proto.RegisterType((*PostAccountRequest)(nil), "pb.PostAccountRequest")
	proto.RegisterType((*PostAccountResponse)(nil), "pb.PostAccountResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "pb.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "pb.GetAccountResponse")
	proto.RegisterType((*GetAccountsRequest)(nil), "pb.GetAccountsRequest")
	proto.RegisterType((*GetAccountsReponse)(nil), "pb.GetAccountsReponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsReponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error) {
	out := new(PostAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.AccountService/PostAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.AccountService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsReponse, error) {
	out := new(GetAccountsReponse)
	err := c.cc.Invoke(ctx, "/pb.AccountService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	PostAccount(context.Context, *PostAccountRequest) (*PostAccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsReponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_PostAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).PostAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AccountService/PostAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).PostAccount(ctx, req.(*PostAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AccountService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AccountService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostAccount",
			Handler:    _AccountService_PostAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _AccountService_GetAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_cf6ab7fb5d06f5ed) }

var fileDescriptor_account_cf6ab7fb5d06f5ed = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xeb, 0x10, 0x51, 0xb8, 0x88, 0x4a, 0x1c, 0xa2, 0x44, 0x9d, 0x2a, 0x23, 0x44, 0x17,
	0x32, 0x94, 0x91, 0x56, 0xc0, 0xc4, 0x8a, 0xc2, 0x13, 0x24, 0xa9, 0x87, 0xa8, 0x22, 0x36, 0x3d,
	0x87, 0x07, 0xe5, 0x89, 0x50, 0x6c, 0x27, 0x18, 0x47, 0x0c, 0x6c, 0xa7, 0xcf, 0xbf, 0xef, 0xfe,
	0x7c, 0x32, 0x9c, 0x15, 0x55, 0x25, 0xdb, 0x46, 0x67, 0xea, 0x20, 0xb5, 0xc4, 0x48, 0x95, 0xfc,
	0x0e, 0xa6, 0xcf, 0x56, 0xc4, 0x19, 0x44, 0xf5, 0x2e, 0x65, 0x4b, 0xb6, 0x3a, 0xcd, 0xa3, 0x7a,
	0x87, 0x08, 0x71, 0x53, 0xbc, 0x8b, 0x34, 0x32, 0x8a, 0xa9, 0xf9, 0x0a, 0xf0, 0x55, 0x92, 0x76,
	0x96, 0x5c, 0x7c, 0xb4, 0x82, 0xf4, 0x40, 0x32, 0x8f, 0xdc, 0xc0, 0xc5, 0x2f, 0x92, 0x94, 0x6c,
	0x48, 0xe0, 0x0d, 0x4c, 0xdd, 0x12, 0x86, 0x4e, 0xd6, 0x49, 0xa6, 0xca, 0xac, 0xa7, 0xfa, 0x37,
	0x7e, 0x0d, 0xe7, 0x2f, 0x22, 0x1c, 0x13, 0x2c, 0xc8, 0x1f, 0x00, 0x7d, 0xe8, 0x7f, 0x13, 0x36,
	0xbe, 0x99, 0xbc, 0x4b, 0x68, 0x5f, 0x2b, 0xe3, 0x8c, 0x73, 0x53, 0x77, 0x9a, 0x2e, 0xf6, 0x36,
	0x87, 0x38, 0x37, 0x35, 0xdf, 0x06, 0x6e, 0x3b, 0xfa, 0x16, 0x4e, 0x5c, 0x7b, 0x4a, 0xd9, 0xf2,
	0x28, 0x9c, 0x3d, 0x3c, 0xae, 0xbf, 0x18, 0xcc, 0x9c, 0xfa, 0x26, 0x0e, 0x9f, 0x75, 0x25, 0xf0,
	0x09, 0x12, 0x2f, 0x2f, 0x9c, 0x77, 0xc6, 0x71, 0xd4, 0x8b, 0xab, 0x91, 0x6e, 0xcf, 0xe6, 0x13,
	0xdc, 0x02, 0xfc, 0xec, 0x84, 0x97, 0x1d, 0x38, 0xca, 0x70, 0x31, 0x0f, 0xe5, 0xc1, 0xfe, 0x08,
	0x89, 0x77, 0x12, 0x06, 0x20, 0xfd, 0xd1, 0xa0, 0xbf, 0x9d, 0x4f, 0xca, 0x63, 0xf3, 0xab, 0xee,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xae, 0x96, 0x05, 0x66, 0x02, 0x00, 0x00,
}
